apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: entorno-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain